### ISSUE TITLE
State of Gentoo OpenRA ebuild

### ISSUE THREAD

**Issue by Beep6581** [cerebrum/dr#8]
Hello

I'm trying to get something moving so that OpenRA-20160508 gets into Portage.
https://bugs.gentoo.org/show_bug.cgi?id=582942

What is the status of the ebuild? Are there any issues with it?

Last time I compiled OpenRA, about a year ago, there was some issue with the package manager OpenRA uses to get the right mono dependencies, I forgot the details, do you know what the situation with that is?

**Comment by cerebrum** [comment]
It does work. But first of all it is recommended to get dotnet overlay and push mono from it into portage (see dependencies in the ebuild and current version of mono in portage).

By default it uses this script from OpenRA authors to get third party dependencies. 
 https://github.com/OpenRA/OpenRA/blob/bleed/thirdparty/fetch-thirdparty-deps.sh
By default it uses noget.sh (curl) to get third-party dependencies but there's also USE-flag to use nuGet for download. This script maybe in a violation of Gentoo rules. Also, there are maybe some repoman issues like with proxy-maintainers herd or games eclass. Otherwise there are no big problems.

**Comment by cerebrum** [comment]
Repoman issues were fixed. Ebuild is migrated to EAPI=6. I'm not going to change the default behaviour of downloading third party dependencies (libraries from nuGet.org and Github etc) using above script. Otherwise it would be harder to maintain it. I'm closing this issue. Open a new one if you still have any problems.

**Comment by Beep6581** [comment]
Thank you for the work @cerebrum !

It's been a year and I don't remember - where do I get this ebuild from? Is it in Portage, or just in an overlay?
